version: '3'
services:
  alexa_apps:
    tty: true
    stdin_open: true
    container_name: "alexa_apps"
    environment:
    - STAGE=dev 
    build:
      context: .
    volumes:
      - ~/.aws:/root/.aws
    entrypoint:
      - "/bin/bash"
